In [17]:
from tensorflow.keras.preprocessing.text import one_hot

In [18]:
### Sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [19]:
## Define the vocabulary size
voc_size=10000


In [20]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7674, 96, 802, 7304],
 [7674, 96, 802, 5426],
 [7674, 9174, 802, 7820],
 [8526, 7230, 2641, 4541, 6274],
 [8526, 7230, 2641, 4541, 1203],
 [833, 7674, 4446, 802, 3757],
 [7172, 4256, 8347, 4541]]

In [21]:
## Word embedding Represemtation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [22]:
import numpy as np

In [23]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7674   96  802 7304]
 [   0    0    0    0 7674   96  802 5426]
 [   0    0    0    0 7674 9174  802 7820]
 [   0    0    0 8526 7230 2641 4541 6274]
 [   0    0    0 8526 7230 2641 4541 1203]
 [   0    0    0  833 7674 4446  802 3757]
 [   0    0    0    0 7172 4256 8347 4541]]


In [24]:
## Feature Representation
dim=10 #dimension

In [25]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)


_________________________________________________________________


In [26]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 93ms/step


array([[[-0.03311634,  0.00813226,  0.0154516 ,  0.04489471,
          0.02222965, -0.01780076,  0.00651733, -0.03524579,
         -0.0152147 ,  0.04647321],
        [-0.03311634,  0.00813226,  0.0154516 ,  0.04489471,
          0.02222965, -0.01780076,  0.00651733, -0.03524579,
         -0.0152147 ,  0.04647321],
        [-0.03311634,  0.00813226,  0.0154516 ,  0.04489471,
          0.02222965, -0.01780076,  0.00651733, -0.03524579,
         -0.0152147 ,  0.04647321],
        [-0.03311634,  0.00813226,  0.0154516 ,  0.04489471,
          0.02222965, -0.01780076,  0.00651733, -0.03524579,
         -0.0152147 ,  0.04647321],
        [-0.0449003 ,  0.00812041, -0.00468049, -0.01324483,
         -0.03506292,  0.04991371, -0.00395302, -0.02210642,
         -0.0385078 ,  0.0217363 ],
        [ 0.01505211, -0.02502484,  0.02666319,  0.00529682,
          0.0488832 , -0.00047102,  0.0018812 ,  0.02908707,
          0.0159488 , -0.02726274],
        [-0.01069624,  0.02728567,  0.0384632 , -0.0

In [27]:
embedded_docs[0]

array([   0,    0,    0,    0, 7674,   96,  802, 7304])

In [30]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 29ms/step


array([[-0.03311634,  0.00813226,  0.0154516 ,  0.04489471,  0.02222965,
        -0.01780076,  0.00651733, -0.03524579, -0.0152147 ,  0.04647321],
       [-0.03311634,  0.00813226,  0.0154516 ,  0.04489471,  0.02222965,
        -0.01780076,  0.00651733, -0.03524579, -0.0152147 ,  0.04647321],
       [-0.03311634,  0.00813226,  0.0154516 ,  0.04489471,  0.02222965,
        -0.01780076,  0.00651733, -0.03524579, -0.0152147 ,  0.04647321],
       [-0.03311634,  0.00813226,  0.0154516 ,  0.04489471,  0.02222965,
        -0.01780076,  0.00651733, -0.03524579, -0.0152147 ,  0.04647321],
       [-0.0449003 ,  0.00812041, -0.00468049, -0.01324483, -0.03506292,
         0.04991371, -0.00395302, -0.02210642, -0.0385078 ,  0.0217363 ],
       [ 0.01505211, -0.02502484,  0.02666319,  0.00529682,  0.0488832 ,
        -0.00047102,  0.0018812 ,  0.02908707,  0.0159488 , -0.02726274],
       [-0.01069624,  0.02728567,  0.0384632 , -0.00428945, -0.04733508,
         0.04645127, -0.04808755,  0.01649045